# runs the specified steps while logged in to the container registry

parameters:
- name: Steps
  type: stepList
  default: []
- name: ContainerRegistry
  type: string
  default: ""

steps:
- task: Docker@2
  inputs:
    containerRegistry: "${{ parameters.ContainerRegistry }}"
    command: "login"
    addPipelineData: false
  displayName: "Log in to build docker image cache container registry"

- ${{ parameters.Steps }}

- task: Docker@2
  inputs:
    containerRegistry: "${{ parameters.ContainerRegistry }}"
    command: "logout"
    addPipelineData: false
  displayName: "Log out of build docker image cache container registry"
  condition: always()
